- name: Installing Nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: Copy Expense Config File
  ansible.builtin.copy:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: Import Common Role - APP Pre-requisities
  ansible.builtin.import_role:
    name: common
    tasks_from: app-prereq
    vars:
      app_dir: /app
      component: frontend

- name: Start Nginx Service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes
